const events = [
    {
      id: 1,
      title: "Holi Festival Celebrations",
      date: "March 14, 2025",
      location: "Mathura and Vrindavan, India",
      image: "/assets/holi.jpg",
    },
    {
      id: 2,
      title: "UPCON 2025",
      date: "March 21, 2025",
      location: "Hotel Double Tree by Hilton, Agra, India",
      image: "/assets/conference.webp",
    },
    {
      id: 3,
      title: "Agra Footwear Expo 2025",
      date: "April 4, 2025",
      location: "Agra, India",
      image: "/assets/expo.png",
    },
    {
      id: 4,
      title: "Sunburn Music Festival",
      date: "December 27, 2025",
      location: "Goa, India",
      image: "/assets/sun.jpeg",
    },
    {
      id: 5,
      title: "Jaipur Literature Festival",
      date: "January 25, 2025",
      location: "Jaipur, India",
      image: "/assets/jlf.png",
    },
    {
      id: 6,
      title: "India Art Fair",
      date: "February 9, 2025",
      location: "New Delhi, India",
      image: "/assets/iaf.png",
    },
    {
      id: 7,
      title: "Bollywood Music Awards",
      date: "June 10, 2025",
      location: "Mumbai, India",
      image: "/assets/music.png",
    },
    {
      id: 8,
      title: "Cricket World Cup Qualifiers",
      date: "September 18, 2025",
      location: "Chennai, India",
      image: "/assets/cup.png",
    },
    {
      id: 9,
      title: "Rann Utsav",
      date: "December 1, 2025",
      location: "Kutch, Gujarat, India",
      image: "/assets/runn.jpg",
    },
    {
      id: 10,
      title: "Goa Carnival",
      date: "February 14, 2025",
      location: "Goa, India",
      image: "/assets/car.png",
    },
    {
      id: 11,
      title: "Kumbh Mela",
      date: "April 5, 2025",
      location: "Haridwar, India",
      image: "/assets/kumbhh.png",
    },
    {
      id: 12,
      title: "International Yoga Day",
      date: "June 21, 2025",
      location: "Rishikesh, India",
      image: "/assets/yoga.png",
    },
    {
      id: 13,
      title: "Taj Mahotsav",
      date: "February 18, 2025",
      location: "Agra, India",
      image: "/assets/taj.png",
    },
    {
      id: 14,
      title: "Durga Puja Festival",
      date: "October 20, 2025",
      location: "Kolkata, India",
      image: "/assets/durgapuja.png",
    },
    {
      id: 15,
      title: "Pushkar Camel Fair",
      date: "November 12, 2025",
      location: "Pushkar, Rajasthan, India",
      image: "/assets/camel.jpg",
    },
    {
      id: 16,
      title: "Diwali Festival",
      date: "October 19, 2025",
      location: "All Over India",
      image: "/assets/diwali.jpg",
    },
    {
      id: 17,
      title: "Filmfare Awards",
      date: "March 1, 2025",
      location: "Mumbai, India",
      image: "/assets/filmf.png",
    },
    {
      id: 18,
      title: "International Trade Fair",
      date: "November 20, 2025",
      location: "Pragati Maidan, New Delhi, India",
      image: "/assets/itf.jpg",
    },
    {
      id: 19,
      title: "Lohri Festival",
      date: "January 13, 2025",
      location: "Punjab, India",
      image: "/assets/lohri.jpg",
    },
    {
      id: 20,
      title: "Chennai Music Festival",
      date: "December 15, 2025",
      location: "Chennai, India",
      image: "/assets/dance.avif",
    },
  ];
  
  export default events;
  